customise Singularity 2.3.1 for HPC-UGent

diff --git a/etc/init b/etc/init
--- a/etc/init
+++ b/etc/init
@@ -21,3 +21,31 @@ fi
 SINGULARITYENV_HISTFILE=""
 
 export SINGULARITYENV_PATH SINGULARITYENV_HISTFILE
+
+# UGent only allow images from user scratch directories
+# and VSC singularity group users.
+# $IMAGE_PATH will be empty if realpath is not able to find
+# $SINGULARITY_IMAGE in the file system.
+IMAGE_PATH="$(/usr/bin/realpath "$SINGULARITY_IMAGE" 2> /dev/null)"
+SINGULARITY_VSC_GROUP="gsingularity"
+
+if [ -z "$IMAGE_PATH" ]; then
+    echo "ERROR: $SINGULARITY_IMAGE is not a valid image" >&2
+    exit 1
+fi
+
+if [[ $IMAGE_PATH =~ /vscmnt/.+_apps/.+|.+/user/(home|data)/.+ ]]; then
+    echo "ERROR: found not allowed path in $IMAGE_PATH" >&2
+    exit 1
+fi
+
+# Detect user groups and allow $SINGULARITY_VSC_GROUP
+if /usr/bin/id -nG | /usr/bin/grep -qw "$SINGULARITY_VSC_GROUP"; then
+    echo "$USER belongs to $SINGULARITY_VSC_GROUP"
+else
+    echo "ERROR: $USER does not belong to $SINGULARITY_VSC_GROUP" >&2
+    exit 2
+fi
+
+# Log user Singularity command for ELK
+/usr/bin/logger -t singularity "user=$USER image=$IMAGE_PATH jobid=${PBS_JOBID:-} cmd=$SINGULARITY_COMMAND"
